library("readxl")
library('dplyr')

db <- read_excel("menoresDeEdad.xlsx")

db$`Departamento de registro`[db$`Departamento de registro`=='1']<-'Guatemala'
db$`Departamento de registro`[db$`Departamento de registro`=='2']<-'El Progreso'
db$`Departamento de registro`[db$`Departamento de registro`=='3']<-'Sacatepéquez'
db$`Departamento de registro`[db$`Departamento de registro`=='4']<-'Chimaltenango'
db$`Departamento de registro`[db$`Departamento de registro`=='5']<-'Escuintla'
db$`Departamento de registro`[db$`Departamento de registro`=='6']<-'Santa Rosa'
db$`Departamento de registro`[db$`Departamento de registro`=='7']<-'Sololá'
db$`Departamento de registro`[db$`Departamento de registro`=='8']<-'Totonicapán'
db$`Departamento de registro`[db$`Departamento de registro`=='9']<-'Quetzaltenango'
db$`Departamento de registro`[db$`Departamento de registro`=='10']<-'Suchitepéquez'
db$`Departamento de registro`[db$`Departamento de registro`=='11']<-'Totonicapán'
db$`Departamento de registro`[db$`Departamento de registro`=='12']<-'Totonicapán'
db$`Departamento de registro`[db$`Departamento de registro`=='13']<-'Huehuetenango'
db$`Departamento de registro`[db$`Departamento de registro`=='14']<-'Quiché'
db$`Departamento de registro`[db$`Departamento de registro`=='15']<-'Baja Verapaz'
db$`Departamento de registro`[db$`Departamento de registro`=='16']<-'Alta Verapaz'
db$`Departamento de registro`[db$`Departamento de registro`=='17']<-'Petén'
db$`Departamento de registro`[db$`Departamento de registro`=='18']<-'Izabal'
db$`Departamento de registro`[db$`Departamento de registro`=='19']<-'Zacapa'
db$`Departamento de registro`[db$`Departamento de registro`=='20']<-'Chiquimula'
db$`Departamento de registro`[db$`Departamento de registro`=='21']<-'Jalapa'
db$`Departamento de registro`[db$`Departamento de registro`=='22']<-'Jutiapa'
db$`Departamento de registro`<-as.factor(db$`Departamento de registro`)

db$`Mes de registro`[db$`Mes de registro`=='1']<-'Enero'
db$`Mes de registro`[db$`Mes de registro`=='2']<-'Febrero'
db$`Mes de registro`[db$`Mes de registro`=='3']<-'Marzo'
db$`Mes de registro`[db$`Mes de registro`=='4']<-'Abril'
db$`Mes de registro`[db$`Mes de registro`=='5']<-'Mayo'
db$`Mes de registro`[db$`Mes de registro`=='6']<-'Junio'
db$`Mes de registro`[db$`Mes de registro`=='7']<-'Julio'
db$`Mes de registro`[db$`Mes de registro`=='8']<-'Agosto'
db$`Mes de registro`[db$`Mes de registro`=='9']<-'Septiembre'
db$`Mes de registro`[db$`Mes de registro`=='10']<-'Octubre'
db$`Mes de registro`[db$`Mes de registro`=='11']<-'Noviembre'
db$`Mes de registro`[db$`Mes de registro`=='12']<-'Diciembre'

db$`Clase de union`[db$`Clase de union`=='1']<-'Comunidad Absoluta'
db$`Clase de union`[db$`Clase de union`=='2']<-'Separacion Absoluta'
db$`Clase de union`[db$`Clase de union`=='3']<-'Comunidad de gananciales'
db$`Clase de union`[db$`Clase de union`=='9']<-'No especificado'

db$`Grupo etnico del hombre`[db$`Grupo etnico del hombre`=='1']<-'Maya'
db$`Grupo etnico del hombre`[db$`Grupo etnico del hombre`=='2']<-'Garifuna'
db$`Grupo etnico del hombre`[db$`Grupo etnico del hombre`=='3']<-'Xinka'
db$`Grupo etnico del hombre`[db$`Grupo etnico del hombre`=='4']<-'Mestizo/Ladino'
db$`Grupo etnico del hombre`[db$`Grupo etnico del hombre`=='5']<-'Otro'
db$`Grupo etnico del hombre`[db$`Grupo etnico del hombre`=='9']<-'Ignorado'

db$`Grupo etnico de la mujer`[db$`Grupo etnico de la mujer`=='1']<-'Maya'
db$`Grupo etnico de la mujer`[db$`Grupo etnico de la mujer`=='2']<-'Garifuna'
db$`Grupo etnico de la mujer`[db$`Grupo etnico de la mujer`=='3']<-'Xinka'
db$`Grupo etnico de la mujer`[db$`Grupo etnico de la mujer`=='4']<-'Mestizo/Ladino'
db$`Grupo etnico de la mujer`[db$`Grupo etnico de la mujer`=='5']<-'Otro'
db$`Grupo etnico de la mujer`[db$`Grupo etnico de la mujer`=='9']<-'Ignorado'

db$`Nacionalidad del hombre`[db$`Nacionalidad del hombre`=='170']<-'Colombia'
db$`Nacionalidad del hombre`[db$`Nacionalidad del hombre`=='222']<-'El Salvador'
db$`Nacionalidad del hombre`[db$`Nacionalidad del hombre`=='320']<-'Guatemala'
db$`Nacionalidad del hombre`[db$`Nacionalidad del hombre`=='340']<-'Honduras'
db$`Nacionalidad del hombre`[db$`Nacionalidad del hombre`=='484']<-'Malta'
db$`Nacionalidad del hombre`[db$`Nacionalidad del hombre`=='566']<-'Portugal'
db$`Nacionalidad del hombre`[db$`Nacionalidad del hombre`=='604']<-'Peru'
db$`Nacionalidad del hombre`[db$`Nacionalidad del hombre`=='68']<-'Bolivia'
db$`Nacionalidad del hombre`[db$`Nacionalidad del hombre`=='720']<-'Nicaragua'
db$`Nacionalidad del hombre`[db$`Nacionalidad del hombre`=='723']<-'Mexico'
db$`Nacionalidad del hombre`[db$`Nacionalidad del hombre`=='84']<-'Belice'
db$`Nacionalidad del hombre`[db$`Nacionalidad del hombre`=='840']<-'USA'

db$`Nacionalidad de la mujer`[db$`Nacionalidad de la mujer`=='124']<-'Canada'
db$`Nacionalidad de la mujer`[db$`Nacionalidad de la mujer`=='222']<-'El Salvador'
db$`Nacionalidad de la mujer`[db$`Nacionalidad de la mujer`=='320']<-'Guatemala'
db$`Nacionalidad de la mujer`[db$`Nacionalidad de la mujer`=='340']<-'Honduras'
db$`Nacionalidad de la mujer`[db$`Nacionalidad de la mujer`=='720']<-'Nicaragua'
db$`Nacionalidad de la mujer`[db$`Nacionalidad de la mujer`=='723']<-'Mexico'
db$`Nacionalidad de la mujer`[db$`Nacionalidad de la mujer`=='840']<-'USA'

db$`Escolaridad del hombre`[db$`Escolaridad del hombre`=='1']<-'Ninguno'
db$`Escolaridad del hombre`[db$`Escolaridad del hombre`=='2']<-'Primaria'
db$`Escolaridad del hombre`[db$`Escolaridad del hombre`=='3']<-'Basico'
db$`Escolaridad del hombre`[db$`Escolaridad del hombre`=='4']<-'Diversificado'
db$`Escolaridad del hombre`[db$`Escolaridad del hombre`=='5']<-'Universitario'
db$`Escolaridad del hombre`[db$`Escolaridad del hombre`=='6']<-'Postgrado'
db$`Escolaridad del hombre`[db$`Escolaridad del hombre`=='9']<-'Ignorado'

db$`Escolaridad de la mujer`[db$`Escolaridad de la mujer`=='1']<-'Ninguno'
db$`Escolaridad de la mujer`[db$`Escolaridad de la mujer`=='2']<-'Primaria'
db$`Escolaridad de la mujer`[db$`Escolaridad de la mujer`=='3']<-'Basico'
db$`Escolaridad de la mujer`[db$`Escolaridad de la mujer`=='4']<-'Diversificado'
db$`Escolaridad de la mujer`[db$`Escolaridad de la mujer`=='5']<-'Universitario'
db$`Escolaridad de la mujer`[db$`Escolaridad de la mujer`=='6']<-'Postgrado'
db$`Escolaridad de la mujer`[db$`Escolaridad de la mujer`=='9']<-'Ignorado'


dbb<-db %>%
  group_by(db$`Ocupacion del hombre`)%>%
  tally()

db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='03']<-'Otros miembros de las fuerzas'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='0310']<-'Otros miembros de las fuerzas'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='1120']<-'Directores ejecutivos, personal directivo de administración pública, miembros del poder ejecutivo y cuerpos legislativos'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='12']<-'Directores administradores y comerciales'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='1219']<-'Directores administradores y comerciales'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='13']<-'Directores y gerentes de producción y operaciones'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='1346']<-'Otros miembros de las fuerzas'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='14']<-'Gerentes de hoteles, restaurantes, comercios y otros servicios'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='1411']<-'Directores ejecutivos, personal directivo de administración pública, miembros del poder ejecutivo y cuerpos legislativos'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='21']<-'Profesionales de las ciencias y de la ingeniería'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2132']<-'Profesionales de las ciencias y de la ingeniería Profesionales de nivel medio de la salud'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2141']<-'Profesionales de las ciencias y de la ingeniería'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2144']<-'Profesionales de las ciencias y de la ingeniería'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2145']<-'Profesionales de las ciencias y de la ingeniería'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2149']<-'Profesionales de las ciencias y de la ingeniería'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2161']<-'Profesionales de las ciencias y de la ingeniería'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2165']<-'Profesionales de las ciencias y de la ingeniería'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='22']<-'Profesionales de la salud'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2166']<-'Profesionales de las ciencias y de la ingeniería'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2250']<-'Profesionales de la salud'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2261']<-'Profesionales de la salud'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2264']<-'Profesionales de la salud'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='23']<-'Profesionales de la enseñanza'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2320']<-'Profesionales de la enseñanza'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2330']<-'Profesionales de la enseñanza'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2341']<-'Profesionales de la enseñanza'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2342']<-'Profesionales de la enseñanza'

db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2262']<-'Profesionales de la salud'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2351']<-'Profesionales de la enseñanza'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2353']<-'Profesionales de la enseñanza'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2354']<-'Profesionales de la enseñanza'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2359']<-'Profesionales de la enseñanza'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='24']<-'Especialistas en organización de la administración publica y de empresas'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2412']<-'Especialistas en organización de la administración publica y de empresas'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2421']<-'Especialistas en organización de la administración publica y de empresas'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2422']<-'Especialistas en organización de la administración publica y de empresas'

db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2356']<-'Profesionales de la enseñanza'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2431']<-'Especialistas en organización de la administración publica y de empresas'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='25']<-'Profesionales de tecnología de la información y las comunicaciones'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='26']<-'Profesionales en derecho, en ciencias sociales y culturales'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2611']<-'Profesionales en derecho, en ciencias sociales y culturales'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2635']<-'Profesionales en derecho, en ciencias sociales y culturales'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2636']<-'Profesionales en derecho, en ciencias sociales y culturales'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2642']<-'Profesionales en derecho, en ciencias sociales y culturales'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2643']<-'Profesionales en derecho, en ciencias sociales y culturales'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2652']<-'Profesionales en derecho, en ciencias sociales y culturales'

db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='2656']<-'Profesionales en derecho, en ciencias sociales y culturales'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='31']<-'Profesionales de las ciencias y la ingeniería de nivel medio'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='310']<-'Profesionales de las ciencias y la ingeniería de nivel medio'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='3114']<-'Profesionales de las ciencias y la ingeniería de nivel medio'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='3115']<-'Profesionales de las ciencias y la ingeniería de nivel medio'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='3118']<-'Profesionales de las ciencias y la ingeniería de nivel medio'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='3119']<-'Profesionales de las ciencias y la ingeniería de nivel medio'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='3122']<-'Profesionales de las ciencias y la ingeniería de nivel medio'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='3123']<-'Profesionales de las ciencias y la ingeniería de nivel medio'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='3139']<-'Profesionales de las ciencias y la ingeniería de nivel medio'


db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='3142']<-'Profesionales de las ciencias y la ingeniería de nivel medio'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='3143']<-'Profesionales de las ciencias y la ingeniería de nivel medio'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='32']<-'Profesionales de las ciencias y la ingeniería de nivel medio'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='3212']<-'Profesionales de nivel medio de la salud'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='3214']<-'Profesionales de nivel medio de la salud'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='3221']<-'Profesionales de nivel medio de la salud'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='3259']<-'Profesionales de nivel medio de la salud'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='33']<-'Profesionales de nivel medio en operaciones financieras y administrativas'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='3314']<-'Profesionales de nivel medio en operaciones financieras y administrativas'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='3322']<-'Profesionales de nivel medio en operaciones financieras y administrativas'

db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='3331']<-'Profesionales de nivel medio en operaciones financieras y administrativas'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='3332']<-'Profesionales de nivel medio en operaciones financieras y administrativas'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='3333']<-'Profesionales de nivel medio en operaciones financieras y administrativas'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='34']<-'Profesionales de nivel medio de servicios jurídicos, sociales, culturales y afines'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='3412']<-'Profesionales de nivel medio de servicios jurídicos, sociales, culturales y afines'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='3421']<-'Profesionales de nivel medio de servicios jurídicos, sociales, culturales y afines'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='3431']<-'Profesionales de nivel medio de servicios jurídicos, sociales, culturales y afines'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='3432']<-'Profesionales de nivel medio de servicios jurídicos, sociales, culturales y afines'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='3434']<-'Profesionales de nivel medio de servicios jurídicos, sociales, culturales y afines'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='3435']<-'Profesionales de nivel medio de servicios jurídicos, sociales, culturales y afines'

db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='35']<-'Técnicos de la tecnología de la información y las comunicaciones'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='3513']<-'Técnicos de la tecnología de la información y las comunicaciones'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='3521']<-'Técnicos de la tecnología de la información y las comunicaciones'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='3522']<-'Técnicos de la tecnología de la información y las comunicaciones'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='41']<-'Oficinistas'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='4120']<-'Oficinistas'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='4131']<-'Oficinistas'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='4132']<-'Oficinistas'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='42']<-'Empleados en trato directo con el público'
db$`Ocupacion del hombre`[db$`Ocupacion del hombre`=='4211']<-'Empleados en trato directo con el público
'

write.csv(db,'db_menores.csv')
